### ISSUE TITLE
Delete GoogleSpeech Folder and put those 2 files outside

### ISSUE THREAD

**Issue by corientdev** [AlboVieira/google-speech-tts#1]
Delete GoogleSpeech Folder and put those 2 files outside. As that gives error of class not found and those folders are not identified by composer.

**Comment by albovieira** [comment]
@corientdev my bad, I update the package on packagist now,
Delete the package and after reinstall run:
`composer dump-autoload -o`

It works fine for me.

**Comment by corientdev** [comment]
wonderful
